kind: ConfigMap
apiVersion: v1
metadata:
  name: micro-2
  namespace: micro-app
data:
  config.yaml: |
    service:
      name: micro-2
    apiConfig:
      port: "80"

    serviceA:
      enabled: true
      url: "http://little-micro-1/api/ping"
      interval: "5s"
