apiVersion: v1
kind: Service
metadata:
  name: little-micro-2
spec:
  selector:
    app: little-micro-2
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
