apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-1
  namespace: micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-1
  template:
    metadata:
      labels:
        app: micro-1
    spec:
      containers:
        - name: micro-1
          image: registry.gitlab.com/puksigon/little-microservice:1.0.1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: micro-1-cm
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: micro-1-cm
          configMap:
            name: micro-1
