apiVersion: v1
kind: Service
metadata:
  name: little-micro-1
  namespace: micro-app
spec:
  selector:
    app: micro-1
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
